'use strict';

const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const test = require('node:test');
const { temporaryDirectory } = require('./helpers/temp.cjs');

async function loadInspect() {
  return import('../tools/game-inspect.mjs');
}

function writeGame(dir, { pluginsJs, rpgCore, pixi } = {}) {
  fs.mkdirSync(path.join(dir, 'js', 'plugins'), { recursive: true });
  fs.mkdirSync(path.join(dir, 'js', 'libs'), { recursive: true });
  fs.writeFileSync(path.join(dir, 'js', 'plugins.js'),
    pluginsJs || 'var $plugins = [];\n');
  if (rpgCore !== null) {
    fs.writeFileSync(path.join(dir, 'js', 'rpg_core.js'),
      rpgCore || '// RPG Maker MV v1.6.1\n');
    fs.writeFileSync(path.join(dir, 'js', 'rpg_managers.js'), '// managers\n');
  }
  if (pixi !== null) {
    fs.writeFileSync(path.join(dir, 'js', 'libs', 'pixi.js'),
      pixi || "PIXI.VERSION = '4.8.9';\n");
  }
}

test('game inspection detects the MV engine, pixi, and enabled plugins', async () => {
  const { inspectGame } = await loadInspect();
  const dir = temporaryDirectory('pmjs-game-');
  writeGame(dir, {
    pluginsJs: `// Generated by RPG Maker.
var $plugins =
[
{"name":"YED_Tiled","status":true,"description":"","parameters":{"text":"]"}},
{"name":"--------------------","status":false,"description":"","parameters":{}},
{"name":"Olivia_HorrorEffects","status":false,"description":"","parameters":{}}
];
while (true) {}
`,
  });
  const registry = path.join(__dirname, '..', 'profiles', 'plugin-adapters.json');
  const inspection = inspectGame(dir, registry);
  assert.equal(inspection.engine, 'mv');
  assert.equal(inspection.mvVersion, '1.6.1');
  assert.equal(inspection.engineVersion, '1.6.1');
  assert.equal(inspection.pixiVersion, '4.8.9');
  assert.equal(inspection.pixiPath, path.join('js', 'libs', 'pixi.js'));
  assert.deepEqual(inspection.enabledPlugins, ['YED_Tiled']);
  assert.deepEqual(inspection.matchedAdapters, [
    { plugin: 'YED_Tiled', modules: ['js/pmjs-plugins/yed/tiled.js'] },
  ]);
});

test('game inspection rejects plugins.js outside the generated JSON form', async () => {
  const { readPluginManifest } = await loadInspect();
  const dir = temporaryDirectory('pmjs-game-regex-');
  writeGame(dir, {
    pluginsJs: 'var $plugins = [\n{"name":"YEP_SlipperyTiles","status":Boolean(1)},\n];',
  });
  assert.throws(() => readPluginManifest(dir), /unsupported generated plugin manifest/);
});

test('generated manifests allow trailing commas without changing string values or executing code', async () => {
  const { readPluginManifest } = await loadInspect();
  const dir = temporaryDirectory('pmjs-game-commas-');
  writeGame(dir, { pluginsJs: 'var $plugins = [{"name":"Literal,]\\\"","status":true,"parameters":{"text":"x,}",},},]; throw new Error("never execute");' });
  assert.deepEqual(readPluginManifest(dir).enabled, ['Literal,]"']);
  for (const literal of ['[,,]', '[{"name":"A"},,]', '[{"name":"A","status":true}, console.log("bad")]']) {
    writeGame(dir, { pluginsJs: 'var $plugins = ' + literal + ';' });
    assert.throws(() => readPluginManifest(dir), /unsupported generated plugin manifest/);
  }
});

test('Pixi inspection closes a failed read before trying the next candidate', async () => {
  const { detectPixiVersion } = await loadInspect();
  const dir = temporaryDirectory('pmjs-game-pixi-read-');
  writeGame(dir);
  const first = path.join(dir, 'js', 'libs', 'pixi.js');
  fs.writeFileSync(path.join(dir, 'js', 'pixi.js'), "PIXI.VERSION = '5.3.0';");
  const open = fs.openSync;
  const read = fs.readSync;
  let failedHandle;
  let closedBeforeFallback = false;
  try {
    fs.openSync = function(file, ...args) {
      if (file === path.join(dir, 'js', 'pixi.js')) {
        assert.throws(() => fs.fstatSync(failedHandle), /EBADF/);
        closedBeforeFallback = true;
      }
      const handle = open.call(fs, file, ...args);
      if (file === first) failedHandle = handle;
      return handle;
    };
    fs.readSync = function(handle, ...args) {
      if (handle === failedHandle && !closedBeforeFallback) throw new Error('read failed');
      return read.call(fs, handle, ...args);
    };
    assert.equal(detectPixiVersion(dir).pixiVersion, '5.3.0');
    assert.equal(closedBeforeFallback, true);
  } finally {
    fs.openSync = open;
    fs.readSync = read;
    if (failedHandle !== undefined) {
      try { fs.closeSync(failedHandle); } catch (error) {
        if (error.code !== 'EBADF') throw error;
      }
    }
  }
});

test('game inspection rejects unknown engines and missing manifests', async () => {
  const { inspectGame, readPluginManifest } = await loadInspect();
  const registry = path.join(__dirname, '..', 'profiles', 'plugin-adapters.json');
  const empty = temporaryDirectory('pmjs-game-empty-');
  fs.mkdirSync(path.join(empty, 'js'), { recursive: true });
  assert.throws(() => inspectGame(empty, registry), /plugin manifest not found/);
  const noEngine = temporaryDirectory('pmjs-game-noengine-');
  writeGame(noEngine, { rpgCore: null, pixi: null });
  const found = inspectGame(noEngine, registry);
  assert.equal(found.engine, 'unknown');
  assert.throws(() => readPluginManifest(empty), /plugin manifest not found/);
});

test('adapter registry rejects duplicates and malformed entries', async () => {
  const { loadAdapterRegistry } = await loadInspect();
  const dir = temporaryDirectory('pmjs-registry-');
  const dupe = path.join(dir, 'dupe.json');
  fs.writeFileSync(dupe, JSON.stringify({ adapters: [
    { plugins: ['A'], modules: ['a.js'] },
    { plugins: ['A'], modules: ['b.js'] },
  ] }));
  assert.throws(() => loadAdapterRegistry(dupe), /duplicate adapter plugin name/);
  const bad = path.join(dir, 'bad.json');
  fs.writeFileSync(bad, JSON.stringify({ adapters: [{ plugins: ['A'] }] }));
  assert.throws(() => loadAdapterRegistry(bad), /requires nonempty plugins and modules arrays/);
  const good = path.join(__dirname, '..', 'profiles', 'plugin-adapters.json');
  assert.ok(loadAdapterRegistry(good).length > 0);
});
